### ISSUE TITLE
Wiki page "Server settings" contains NO details about PM Regex

### ISSUE THREAD

**Issue by RAnders00** [killjoy1221/tabbychat#16]
I am trying to get this to work on my custom server for quite a white now, and I have no idea how it works. You forked the wiki with the repo, please keep it updated as well as the code (good documentation really makes up a good software or MC mod)

Please explain to me:
How does the regex work? I have regex that matches every PM chat line, do I need it to return something somehow? I just read about [this](http://stackoverflow.com/a/628563), is that what needs to be done?

Practical example:
I have a server that formats its PM-Messages as:

```
SomeExampleDude messages You: My Message is nice, man, i love pms
You message SomeExampleDude: Yeah i think so as well
```

A regex for the first one would be:

```
/\w+\smessages\syou:\s\w+/
```

And for the second one:

```
/You\smessage\s\w+:\s\w+/
```

This is definitely not correct because it does not work. Can you pass me the two valid entries and update the wiki, please?
![image](http://i.imgur.com/80O5IT4.png)
@killjoy1221

**Comment by mattmess1221** [comment]
The filters are fairly basic and only support static channels. That means you can't use names discovered from the expression. Since you're trying to add what looks like a PM filter, I suggest using the custom pm regex in the server tab.

You would use a pattern such as this:

```
^{$player} messages you: 
^You message {$player}:
```

In the code, `{$player}` is replaced with `([\p{L}\p{N}_]{3,16})`

**Comment by mattmess1221** [comment]
Done.
